[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  

[[redirects]]
  from = "/pfa/*"
  to = "https://proxy-redirect-test.netlify.app/pfa/index.html 200" 
  status = 200
  force = true
