import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Loyola Center for Criminal Justice Policy</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Loyola University Chicago <a href='https://www.luc.edu/ccj/'>CCJ</a>
        </h1>

        <p className={styles.description}>
          Projects and applications developed by the<br></br>Loyola University Chicago Center for Criminal Justice Research
        </p>

        <div className={styles.grid}>
          <a href='https://loyolaccj.org/pfa' className={styles.card}>
            <h2>Pretrial Fairness Act Tracker</h2>
            <p>We're tracking how the PFA impacts bond court outcomes, pretrial, and jail population across Illinois.</p>
          </a>

          <a href='https://charleston-disparity-in-prosecution.org/' className={styles.card}>
            <h2>Disparity and Prosecution in Charleston, SC</h2>
            <p>Report on Charleston County, South Carolina prosecutorial decisions. </p>
          </a>

          <a
            href='https://data.mkedao.com/'
            className={styles.card}
          >
            <h2>Milwaukee DA Dashboard </h2>
            <p>Key indicators on how the justice system functions in Milwaukee from referral and arrest to sentencing. </p>
          </a>

          <a
            href='https://www.covidcrime-chicago.com/'
            className={styles.card}
          >
            <h2>Covid-19's Effect on Chicago Crime </h2>
            <p>
            Project tracks the effect of 2019-nCoV Containment Policies on crime trends in Chicago.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
